// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/5/2025, 11:16:49 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Usach/citiaps/task-system/nuxt3-template/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Usach/citiaps/task-system/nuxt3-template/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Usach/citiaps/task-system/nuxt3-template/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Usach/citiaps/task-system/nuxt3-template/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Usach/citiaps/task-system/nuxt3-template/plugins/**/*.{js,ts,mjs}","C:/Usach/citiaps/task-system/nuxt3-template/composables/**/*.{js,ts,mjs}","C:/Usach/citiaps/task-system/nuxt3-template/utils/**/*.{js,ts,mjs}","C:/Usach/citiaps/task-system/nuxt3-template/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Usach/citiaps/task-system/nuxt3-template/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Usach/citiaps/task-system/nuxt3-template/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Usach/citiaps/task-system/nuxt3-template/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;